/**
 * Scans src/ for all solar:* and circle-flags:* icon references,
 * extracts their data from @iconify-json packages, and generates
 * src/lib/icons.ts with only the icons actually used in the codebase.
 *
 * Usage: node scripts/generate-icons.mjs
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs"
import { join, resolve } from "path"
import { getIconData } from "@iconify/utils"

const ROOT = resolve(import.meta.dirname, "..")
const SRC_DIR = join(ROOT, "src")
const OUTPUT = join(SRC_DIR, "lib", "icons.ts")

function walkFiles(dir, extensions) {
  const results = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const stat = statSync(full)
    if (stat.isDirectory()) {
      results.push(...walkFiles(full, extensions))
    } else if (extensions.some((ext) => full.endsWith(ext))) {
      results.push(full)
    }
  }
  return results
}

const ICON_SETS = [
  { prefix: "solar", pattern: /solar:([a-z0-9-]+)/g, package: "solar" },
  { prefix: "circle-flags", pattern: /circle-flags:([a-z0-9-]+)/g, package: "circle-flags" },
]

// 1. Scan source files for all icon references
const files = walkFiles(SRC_DIR, [".ts", ".tsx"])

const iconsBySet = new Map()
for (const set of ICON_SETS) {
  iconsBySet.set(set.prefix, new Set())
}

for (const file of files) {
  if (resolve(file) === resolve(OUTPUT)) continue

  const content = readFileSync(file, "utf-8")
  for (const set of ICON_SETS) {
    for (const match of content.matchAll(set.pattern)) {
      iconsBySet.get(set.prefix).add(match[1])
    }
  }
}

// For circle-flags, also include all country codes from countries.ts
// since they are generated dynamically via template literals
const countriesPath = join(SRC_DIR, "lib", "countries.ts")
const countriesContent = readFileSync(countriesPath, "utf-8")
const countryCodePattern = /code:\s*"([A-Z]{2})"/g
for (const match of countriesContent.matchAll(countryCodePattern)) {
  iconsBySet.get("circle-flags").add(match[1].toLowerCase())
}

// Also include currency flag codes from currency.ts
const currencyPath = join(SRC_DIR, "lib", "currency.ts")
const currencyContent = readFileSync(currencyPath, "utf-8")
const flagCodePattern = /flagCode:\s*"([a-z0-9-]+)"/g
for (const match of currencyContent.matchAll(flagCodePattern)) {
  iconsBySet.get("circle-flags").add(match[1])
}

// 2. Load icon sets and extract data
const allEntries = []
const allMissing = []

for (const set of ICON_SETS) {
  const names = iconsBySet.get(set.prefix)
  if (names.size === 0) continue

  const iconsJsonPath = join(ROOT, "node_modules", "@iconify-json", set.package, "icons.json")
  const iconSet = JSON.parse(readFileSync(iconsJsonPath, "utf-8"))

  for (const name of [...names].sort()) {
    const data = getIconData(iconSet, name)
    if (!data) {
      allMissing.push(`${set.prefix}:${name}`)
      continue
    }
    allEntries.push({ prefix: set.prefix, name, data })
  }
}

if (allEntries.length === 0) {
  console.error("No icons found in src/")
  process.exit(1)
}

if (allMissing.length > 0) {
  console.warn(`Warning: icons not found: ${allMissing.join(", ")}`)
}

// 3. Generate the output file
const solarCount = allEntries.filter((e) => e.prefix === "solar").length
const flagCount = allEntries.filter((e) => e.prefix === "circle-flags").length

const lines = [
  "// Auto-generated by scripts/generate-icons.mjs - do not edit manually",
  `// ${solarCount} icons from @iconify-json/solar, ${flagCount} from @iconify-json/circle-flags`,
  "",
  'import { addIcon } from "@iconify/react"',
  "",
]

for (const { prefix, name, data } of allEntries) {
  lines.push(`addIcon("${prefix}:${name}", ${JSON.stringify(data)})`)
}

lines.push("")

writeFileSync(OUTPUT, lines.join("\n"), "utf-8")
console.log(`Generated ${OUTPUT} with ${solarCount} solar icons and ${flagCount} circle-flags icons`)
