/**
 * Scans src/ for all solar:* icon references, extracts their data
 * from @iconify-json/solar, and generates src/lib/icons.ts with
 * only the icons actually used in the codebase.
 *
 * Usage: node scripts/generate-icons.mjs
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs"
import { join, resolve } from "path"
import { getIconData } from "@iconify/utils"

const ROOT = resolve(import.meta.dirname, "..")
const SRC_DIR = join(ROOT, "src")
const OUTPUT = join(SRC_DIR, "lib", "icons.ts")

function walkFiles(dir, extensions) {
  const results = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const stat = statSync(full)
    if (stat.isDirectory()) {
      results.push(...walkFiles(full, extensions))
    } else if (extensions.some((ext) => full.endsWith(ext))) {
      results.push(full)
    }
  }
  return results
}

// 1. Scan source files for all solar:* icon references
const files = walkFiles(SRC_DIR, [".ts", ".tsx"])
const iconPattern = /solar:([a-z0-9-]+)/g
const iconNames = new Set()

for (const file of files) {
  // Skip the generated output file itself
  if (resolve(file) === resolve(OUTPUT)) continue

  const content = readFileSync(file, "utf-8")
  for (const match of content.matchAll(iconPattern)) {
    iconNames.add(match[1])
  }
}

if (iconNames.size === 0) {
  console.error("No solar icons found in src/")
  process.exit(1)
}

// 2. Load the full Solar icon set from node_modules
const iconsJsonPath = join(ROOT, "node_modules", "@iconify-json", "solar", "icons.json")
const iconSet = JSON.parse(readFileSync(iconsJsonPath, "utf-8"))

// 3. Extract data for each used icon
const entries = []
const missing = []

for (const name of [...iconNames].sort()) {
  const data = getIconData(iconSet, name)
  if (!data) {
    missing.push(name)
    continue
  }
  entries.push({ name, data })
}

if (missing.length > 0) {
  console.warn(`Warning: icons not found in Solar set: ${missing.join(", ")}`)
}

// 4. Generate the output file
const lines = [
  "// Auto-generated by scripts/generate-icons.mjs - do not edit manually",
  `// ${entries.length} icons extracted from @iconify-json/solar`,
  "",
  'import { addIcon } from "@iconify/react"',
  "",
]

for (const { name, data } of entries) {
  lines.push(`addIcon("solar:${name}", ${JSON.stringify(data)})`)
}

lines.push("")

writeFileSync(OUTPUT, lines.join("\n"), "utf-8")
console.log(`Generated ${OUTPUT} with ${entries.length} icons`)
